/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class glous_kleebot_services_api_HardwareInfo */

#ifndef _Included_glous_kleebot_services_api_HardwareInfo
#define _Included_glous_kleebot_services_api_HardwareInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getCpuModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_glous_kleebot_services_api_HardwareInfo_getCpuModel
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getCpuUsage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_glous_kleebot_services_api_HardwareInfo_getCpuUsage
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getCpuClockCycle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_glous_kleebot_services_api_HardwareInfo_getCpuClockCycle
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getCpuAvailableCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_glous_kleebot_services_api_HardwareInfo_getCpuAvailableCores
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getTotalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_glous_kleebot_services_api_HardwareInfo_getTotalMemory
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getAvailableMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_glous_kleebot_services_api_HardwareInfo_getAvailableMemory
  (JNIEnv *, jobject);

/*
 * Class:     glous_kleebot_services_api_HardwareInfo
 * Method:    getProcessID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_glous_kleebot_services_api_HardwareInfo_getProcessID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
